version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "60:37:35:9a:d6:e8:5f:15:b9:b9:6f:f0:4a:99:6a:8f"
      - checkout
      - run:
          name: Install Dependencies
          command: |
            ssh-add -D
            ssh-add ~/.ssh/id_rsa_6037359ad6e85f15b9b96ff04a996a8f
            git submodule init
            git submodule update
            sudo apt-get install libgmp-dev
            sudo apt-get install libmpfr-dev
            sudo apt-get install libmpc-dev
            python -m pip install --upgrade pip
            pip install -e electionguard-python
            pip install tox tox-gh-actions
      - run:
          name: Test with tox
          command: |
            tox
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
