version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "60:37:35:9a:d6:e8:5f:15:b9:b9:6f:f0:4a:99:6a:8f"
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get install libgmp-dev
            sudo apt-get install libmpfr-dev
            sudo apt-get install libmpc-dev
            python -m pip install --upgrade pip
            make environment
      - run:
          name: Install Modules
          command: |
            make install validate
      - run:
          name: Lint
          command: |
            make lint
      - run:
          name: Test
          command: |
            make coverage

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
